### ISSUE TITLE
Crash without error if a Proxy object is sent through interprocess

### ISSUE THREAD

**Issue by michael-dm** [daltonmenezes/interprocess#3]
If you return a proxy object (for example a reactive object in vue) in a Renderer handler, the webview crashes without outputting any error in main or renderer.

**Comment by daltonmenezes** [comment]
Hi @michael-dm , have you tried that using raw Electron IPCs?

From the Electron docs:

> Electron's IPC implementation uses the HTML standard [Structured Clone Algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to serialize objects passed between processes, meaning that only certain types of objects can be passed through IPC channels.

Probably, that is the case, because Proxy Objects are not Plain Objects, and it is not serializable as far as I know! About the crash, maybe it's an Electron issue from the version you are using, but it requires investigation.

See:
- [docs](https://www.electronjs.org/pt/docs/latest/tutorial/ipc#object-serialization)
- [The structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#javascript_types)

**Comment by michael-dm** [comment]
Yes I'll use `toRaw`, thanks 👍
